[book]
authors = ["Soma Contributors"]
language = "en"
src = "src"
title = "S‚ùçMA"


# [build]
# create-missing = false

# [preprocessor.index]

# [preprocessor.links]

# [output.html]
# site-url = "/"
# git-repository-url = "https://github.com/soma-org/book"
# edit-url-template = "https://github.com/soma-org/book/edit/main/{path}"
# default-theme = "ayu"
# preferred-dark-theme = "ayu"
# git-repository-icon = "fa-github"
